# Opis skryptów 

Skrypt skraping.R służy do ściągnięcia potrzebnych nam danych i umieszczeniu ich w 3 data.framach, których opis umieszczam poniżej.

## Data.frame team_names

Data.frame, który zawiera następujące kolumny:

* name - aktualna nazwa drużyny
* shortage - aktualny skrót nazwy drużyny
* change_year - rok od którego zaczęła obowiązywać aktualna nazwa, jeśli NA to znaczy, ze od dawna
* previous_name - poprzednia nazwa drużyny, NA jeśli w rok.zmian NA
* previous_shortcut - skrót poprzedniej nazwy drużyny, NA jeśli w rok.zmian NA

## Data.frame stats

Data.frame, który zawiera następujące kolumny:

* Team - nazwa drużyny
* G - liczba rozegranych meczy
* MP - liczba rozegranych minut
* FG - liczba trafionych koszy
* FGA - liczba oddanych rzutów
* FG% - procent trafionych rzutów
* 3P - liczba trafionych rzutów za 3
* 3PA - liczba oddanych rzutów za 3
* 3P% - procent trafionych rzutów za 3
* 2P - liczba trafionych rzutów za 2
* 2PA - liczba oddanych rzutów za 2
* 2P% - procent trafionych rzutów za 2
* FT - liczba trafionych rzutów osobistych
* FTA - liczba oddanych rzutów osobistych
* FT% - procent trafionych rzutów osobistych
* ORB - zbiórki w ataku
* DRB - zbiórki w obronie 
* TRB - zbiórki ogółem
* AST - asysty
* STL - przechwyty
* BLK - bloki
* TOV - straty
* PF - faule osobiste
* PTS - punkty ogółem
* PTS/G - średnia punktów na mecz
* OFG - liczba trafionych koszy drużyn przeciwnych
* OFGA - liczba oddanych rzutów drużyn przeciwnych
* OFG% - procent trafionych rzutów drużyn przeciwnych
* O3P - liczba trafionych rzutów za 3 drużyn przeciwnych
* O3PA - liczba oddanych rzutów za 3 drużyn przeciwnych
* O3P% - procent trafionych rzutów za 3 drużyn przeciwnych
* O2P - liczba trafionych rzutów za 2 drużyn przeciwnych
* O2PA - liczba oddanych rzutów za 2 drużyn przeciwnych
* O2P% - procent trafionych rzutów za 2 drużyn przeciwnych
* OFT - liczba trafionych rzutów osobistych drużyn przeciwnych
* OFTA - liczba oddanych rzutów osobistych drużyn przeciwnych
* OFT% - procent trafionych rzutów osobistych drużyn przeciwnych
* OORB - zbiórki w ataku drużyn przeciwnych
* ODRB - zbiórki w obronie drużyn przeciwnych 
* OTRB - zbiórki ogółem drużyn przeciwnych
* OAST - asysty drużyn przeciwnych
* OSTL - przechwyty drużyn przeciwnych
* OBLK - bloki drużyn przeciwnych
* OTOV - straty drużyn przeciwnych
* OPF - faule osobiste drużyn przeciwnych
* OPTS - punkty ogółem drużyn przeciwnych
* OPTS/G - średnia punktów na mecz drużyn przeciwnych
* Age- średni wiek zawodników
* PW - przewidywana liczba zwycięstw
* PL - przewidywana liczba porażek
* MOV - zmienna, określająca średnio jak duże było nasze zwycięstwo/przegrana (czy 40pkt czy 2)
* SOS - układ grafiku meczy, jeśli 0 to przeciętny, jeśli plus to korzystny, jeśli minus to niesprzyjający 
* SRS - zmienna, która jest kombinacją dwóch poprzednich
* ORtg - przewidywana liczba punktów, która będzie zdobyta na 100 akcji ofensywnych 
* DRtg - przewidywana liczba punktów, którą pozwolą zdobyć przeciwnikom na 100 akcji defensywnych
* FTr - stosunek liczby rzutów osobistych do liczby rzutów
* 3PAr - stosunek liczby rzutów za 3 do liczby rzutów
* TS% - efektywność rzutów 
* eFG% - zmienna uwzględniająca fakt że rzut za 3 ma większe ryzyko, ale większy zysk
* TOV% - przewidywana liczba strat na 100 akcji ofensywnych
* ORB% - przewidywany procent akcji zakończonych nietrafionym rzutem, w którym uda nam się zebrać w ofensywie piłkę
* FT/FGA - 
* eFG%.1 - to samo co eFG%, tylko dla drużyn przeciwnych
* TOV%.1 - to samo co TOV%, tylko dla drużyn przeciwnych
* DRB% - przewidywany procent akcji zakończonych nietrafionym rzutem przeciwników, w którym uda nam się zebrać piłkę w defensywie
* FT/FGA.1 - 
* Arena - nazwa stadionu
* Attendance - suma liczby kibiców z każdego meczu

## Data.frame games_history

Data.frame, który zawiera następujące kolumny:
* Host - Skrót nazwy drużyny gospodarzy
* Opponent - Skrót nazwy drużyny gości
* Date - Data meczu
* Tm - Liczba punktów zdobytych przez gospodarzy
* Opp - Liczba punktów zdobytych przez gości
* Result - Rezultat meczu (W to wygrana gospodarzy , L to wygrana gości)
* Year - Sezon rozegrania meczu

## Lista team_story

Jest to lista zawierająca 30 data.framów o nazwach drużyn. Każdy z nich odpowiada 5 letniej historii meczów dla zespołu.

W każdym data.framie znajdują sie kolumny:
* Opponent- Nazwa drużyny przeciwnej
* Date - Data meczu
* Tm - Liczba zdobytych punktów przez daną drużynę
* Opp - Liczba zdobytych punktów przez drużynę przeciwną 
* L - Ile włącznie z tym meczem dana drużyna odniosła porażek w danym sezonie
* Result - Wynik meczu
* Where - Jeśli @ to na wyjeździe, jeśli pusto to w domu
* Year - Rok

#Skrypt bazaFunkcje.R umożliwia automatyczne utworzenie i zapełnienie bazy scrapowanymi danymi
#Należy go wykonać po wcześniejszym source skraping.R
#Celem wgrania środowiska i utworzenia bazy wykonuje się funkcję setupEnvironment()



